spring.application.name=Backend-UVote

# ============================
# SERVER
# ============================
server.port=${PORT:8080}

# ============================
# BASE DE DATOS
# ============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================
# JPA / HIBERNATE
# ============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ============================
# JWT
# ============================
uvote.jwt.secret=${JWT_SECRET}
uvote.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

# ============================
# LOGGING
# ============================
logging.level.org.springframework.security=INFO

# ============================
# ARCHIVOS
# ============================
app.upload-dir=${APP_UPLOAD_DIR:uploads}

# ============================
# RESEND API
# ============================
resend.api-key=${RESEND_API_KEY}

# ============================
# APP MAIL
# ============================
app.mail.from=${APP_MAIL_FROM}